# Cấu hình trang GitHub Pages — sinh viên chỉ cần sửa ba dòng đầu
title: Trần Nguyễn Minh Khang
description: trannquyznminhkhang23208@gmail.com
author: trannquyznminhkhang23208.github.io

theme: jekyll-theme-cayman
lang: vi

# Đừng sửa phần dưới trừ khi em biết mình đang làm gì
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - .gitignore
